version: 2
jobs:
  00-login:
    macos:
      xcode: "10.0.0"
    environment:
          LC_ALL: en_US.UTF-8
          LANG: en_US.UTF-8
          HOMEBREW_LOGS: ~/homebrew-logs
          HOMEBREW_TEMP: ~/homebrew-temp
    steps:
      - checkout
      - run: |
          brew install swiftlint
          sudo gem install
          bundle install --without development
          grep -lR "shouldUseLaunchSchemeArgsEnv" *.* --null | xargs -0 sed -i '' -e 's/shouldUseLaunchSchemeArgsEnv = "YES"/shouldUseLaunchSchemeArgsEnv = "YES" codeCoverageEnabled = "YES"/g'
      - run:
          name: Bootstrap
          command: bundle exec fastlane ios bootstrap
      - run:
          name: Run test suite
          command: bundle exec fastlane ios ci
          environment:
            SCHEME: Auth0.iOS
            DEVICE: iPhone 8
            FASTLANE_EXPLICIT_OPEN_SIMULATOR: 2
      - run: |
          bash <(curl -s https://codecov.io/bash) -J 'Auth0'
      - save_cache:
          key: dependency-cache
          paths:
            - Carthage/Build
      - store_test_results:
          path: fastlane/test_output

workflows:
  version: 2
  build:
    jobs:
      -  00-login